#fail
class Foo():
	def foo(self):
		print('a')
Foo().foo()
#out: a
